/**
 * Copyright (c) 2026 HOOX · HOOX · jango-blockchained (hoox-sh)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Shared keys subcommand registration for:
 *   - `hoox config keys …`
 *   - `hoox keys …` (top-level alias, in-process — no PATH re-spawn)
 */
import { chmodSync, existsSync, readFileSync } from "node:fs";
import type { Command } from "commander";

import { withErrorHandling } from "../../utils/error-handler.js";
import {
  formatSuccess,
  formatKeyValue,
  formatJson,
  getFormatOptions,
} from "../../utils/formatters.js";
import { ensureSecretDir, secureSecretFile } from "../../utils/fs-secure.js";
import { theme } from "../../utils/theme.js";

/** Generate a cryptographically random hex key of the specified byte length. */
function generateKey(bytes = 32): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, "0")).join("");
}

/**
 * Which mesh keys each worker needs in `.dev.vars`.
 * Keep aligned with SetupService DEV_VARS_WORKER_KEYS.
 */
const DEV_VARS_WORKER_KEYS: Record<string, string[]> = {
  "d1-worker": ["INTERNAL_KEY_BINDING"],
  "analytics-worker": ["INTERNAL_KEY_BINDING"],
  "trade-worker": [
    "INTERNAL_KEY_BINDING",
    "TELEGRAM_INTERNAL_KEY_BINDING",
    "API_SERVICE_KEY_BINDING",
  ],
  "report-worker": ["INTERNAL_KEY_BINDING"],
  "email-worker": ["INTERNAL_KEY_BINDING"],
  "agent-worker": ["INTERNAL_KEY_BINDING", "AGENT_INTERNAL_KEY"],
  hoox: ["INTERNAL_KEY_BINDING", "WEBHOOK_API_KEY_BINDING"],
  "web3-wallet-worker": ["INTERNAL_KEY_BINDING"],
  "telegram-worker": ["INTERNAL_KEY_BINDING"],
  dashboard: [
    "AGENT_INTERNAL_KEY",
    "SESSION_SECRET",
    "TRADE_INTERNAL_KEY",
    "API_SERVICE_KEY_BINDING",
  ],
};

const WORKER_FS_DIR: Record<string, string> = {
  hoox: "hoox-worker",
};

function workerFsDir(worker: string): string {
  return WORKER_FS_DIR[worker] ?? worker;
}

function parseEnvFile(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    map.set(trimmed.slice(0, eq), trimmed.slice(eq + 1));
  }
  return map;
}

/**
 * Merge mesh keys into each worker's `.dev.vars` (preserves integration secrets).
 * Returns the number of files written.
 */
async function writeDevVarsFromKeys(
  keys: Record<string, string>
): Promise<number> {
  let count = 0;
  for (const [worker, secretNames] of Object.entries(DEV_VARS_WORKER_KEYS)) {
    const path = `workers/${workerFsDir(worker)}/.dev.vars`;
    const meshSet = new Set(secretNames);
    const existing = existsSync(path)
      ? parseEnvFile(readFileSync(path, "utf-8"))
      : new Map<string, string>();

    for (const secretName of secretNames) {
      const value = keys[secretName];
      if (value) existing.set(secretName, value);
    }

    let content = `# .dev.vars — local secrets for ${worker}\n`;
    content += `# Generated by \`hoox keys generate\`. NEVER commit this file.\n\n`;
    for (const secretName of secretNames) {
      const value = existing.get(secretName);
      if (value !== undefined) content += `${secretName}=${value}\n`;
    }
    for (const [k, v] of existing) {
      if (!meshSet.has(k)) content += `${k}=${v}\n`;
    }

    await Bun.write(path, content);
    try {
      chmodSync(path, 0o600);
    } catch {
      // ignore chmod failures (Windows / restricted FS)
    }
    count++;
  }
  return count;
}

/**
 * Attach generate / list under a parent command
 * (either `config keys` or top-level `keys`).
 */
export function registerKeysSubcommands(
  keysCmd: Command,
  service = "config"
): void {
  keysCmd
    .command("generate")
    .summary("Generate new internal auth keys")
    .description(
      `Generate new internal auth keys and save to .keys/ directory.

Creates the following keys (aligned with setup / SYSTEM_SECRET_NAMES):
  - INTERNAL_KEY_BINDING          (32-byte hex, shared mesh)
  - AGENT_INTERNAL_KEY            (same as INTERNAL)
  - TELEGRAM_INTERNAL_KEY_BINDING (same as INTERNAL)
  - TRADE_INTERNAL_KEY            (same as INTERNAL)
  - API_SERVICE_KEY_BINDING       (same as INTERNAL)
  - WEBHOOK_API_KEY_BINDING       (32-byte hex, distinct)
  - SESSION_SECRET                (64-byte hex, distinct)

WARNING: Add .keys/ to your .gitignore to avoid committing secrets!

EXAMPLES:
  hoox keys generate
  hoox config keys generate`
    )
    .action(
      withErrorHandling(
        async (_, cmd: Command) => {
          const opts = getFormatOptions(cmd);

          const keysDir = ".keys";
          ensureSecretDir(keysDir);

          // Shared mesh key strategy (matches SetupService.generateKeys).
          const meshKey = generateKey();
          const keys: Record<string, string> = {
            INTERNAL_KEY_BINDING: meshKey,
            AGENT_INTERNAL_KEY: meshKey,
            TELEGRAM_INTERNAL_KEY_BINDING: meshKey,
            TRADE_INTERNAL_KEY: meshKey,
            API_SERVICE_KEY_BINDING: meshKey,
            WEBHOOK_API_KEY_BINDING: generateKey(),
            SESSION_SECRET: generateKey(64),
          };

          for (const [name, value] of Object.entries(keys)) {
            const filePath = `${keysDir}/${name.toLowerCase()}.env`;
            await Bun.write(filePath, `${name}=${value}\n`);
            secureSecretFile(filePath);
          }
          // Combined setup.env for setup --skip-keys reloads
          await Bun.write(
            `${keysDir}/setup.env`,
            "# Generated by hoox keys generate\n" +
              Object.entries(keys)
                .map(([k, v]) => `${k}=${v}`)
                .join("\n") +
              "\n"
          );
          secureSecretFile(`${keysDir}/setup.env`);

          // Also merge into each worker's .dev.vars so
          // `hoox secrets sync --system` can read values (dashboard docs
          // recommend: keys generate && secrets sync --system).
          const devVarsCount = await writeDevVarsFromKeys(keys);

          formatSuccess(
            `Generated ${Object.keys(keys).length} keys in ${keysDir}/ + ${devVarsCount} .dev.vars`,
            opts
          );

          if (!opts.quiet && !opts.json) {
            process.stdout.write(
              `${theme.warning("!")}  Keep these keys secret. Add ${keysDir}/ to .gitignore.\n`
            );
            process.stdout.write(
              `${theme.dim("→")}  Next: hoox secrets sync --system\n`
            );
            formatKeyValue(keys, opts);
          }
        },
        { service }
      )
    );

  keysCmd
    .command("list")
    .summary("List existing internal auth keys")
    .description(
      `List existing internal auth keys from the .keys/ directory.

Shows key names (values are hidden for security).

EXAMPLES:
  hoox keys list
  hoox config keys list`
    )
    .action(
      withErrorHandling(
        async (_, cmd: Command) => {
          const opts = getFormatOptions(cmd);

          const keysDir = ".keys";
          if (!existsSync(keysDir)) {
            process.stdout.write(
              `${theme.dim("No .keys/ directory found.")}\n`
            );
            return;
          }

          const glob = new Bun.Glob("*.env");
          const entries: string[] = [];
          for await (const f of glob.scan({ cwd: keysDir, absolute: false })) {
            entries.push(f);
          }

          if (entries.length === 0) {
            process.stdout.write(
              `${theme.dim("No key files found in .keys/")}\n`
            );
            return;
          }

          const keyMap: Record<string, string> = {};
          for (const entry of entries) {
            const filePath = `${keysDir}/${entry}`;
            const content = await (await Bun.file(filePath).text()).trim();
            const eqIdx = content.indexOf("=");
            if (eqIdx > 0) {
              keyMap[content.substring(0, eqIdx)] = "****";
            }
          }

          if (opts.json) {
            formatJson({ keys: entries.length, files: entries }, opts);
          } else {
            process.stdout.write(
              `${theme.heading(`\nKey files in ${keysDir}/`)}\n`
            );
            formatKeyValue(keyMap, opts);
          }
        },
        { service }
      )
    );
}
