/**
 * Copyright (c) 2026 HOOX · HOOX · jango-blockchained (hoox-sh)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * DEX P1 setup helpers: Solana seed generation and public RPC defaults.
 * No @solana/* SDK — 32-byte seed (wallet worker expands via tweetnacl).
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";

const B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

export const DEFAULT_RPC_URL_ARBITRUM = "https://arbitrum.llamarpc.com";
export const DEFAULT_RPC_URL_SOLANA = "https://solana-rpc.publicnode.com";

/** Bitcoin-style Base58 encode (Solana secret/seed format). */
export function encodeBase58(bytes: Uint8Array): string {
  if (bytes.length === 0) return "";
  const digits = [0];
  for (const byte of bytes) {
    let carry = byte;
    for (let j = 0; j < digits.length; j++) {
      carry += (digits[j] as number) * 256;
      digits[j] = carry % 58;
      carry = Math.floor(carry / 58);
    }
    while (carry > 0) {
      digits.push(carry % 58);
      carry = Math.floor(carry / 58);
    }
  }
  let zeros = 0;
  for (const b of bytes) {
    if (b === 0) zeros++;
    else break;
  }
  if (zeros === bytes.length) return "1".repeat(zeros);
  // digits is little-endian; skip the dummy high zero from the initial [0]
  let i = digits.length - 1;
  while (i > 0 && digits[i] === 0) i--;
  let out = "1".repeat(zeros);
  for (; i >= 0; i--) out += B58[digits[i] as number] ?? "";
  return out;
}

/** 32-byte ed25519 seed as base58 (Phantom-compatible via wallet fromSeed). */
export function generateSolanaSeedBase58(): string {
  const seed = new Uint8Array(32);
  crypto.getRandomValues(seed);
  return encodeBase58(seed);
}

function parseEnvFile(text: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    map.set(trimmed.slice(0, eq), trimmed.slice(eq + 1));
  }
  return map;
}

/**
 * If `.dev.vars` has no SOLANA_PRIVATE_KEY, generate a seed and append it.
 * Never overwrites an existing value.
 */
export function ensureSolanaPrivateKey(devVarsPath: string): {
  generated: boolean;
  value: string | null;
} {
  const existing = existsSync(devVarsPath)
    ? parseEnvFile(readFileSync(devVarsPath, "utf-8"))
    : new Map<string, string>();
  const current = existing.get("SOLANA_PRIVATE_KEY")?.trim();
  if (current) return { generated: false, value: current };

  const value = generateSolanaSeedBase58();
  const header = existsSync(devVarsPath)
    ? readFileSync(devVarsPath, "utf-8")
    : "# .dev.vars — local secrets\n# Generated by `hoox setup`. NEVER commit.\n\n";
  const sep = header.endsWith("\n") ? "" : "\n";
  writeFileSync(
    devVarsPath,
    `${header}${sep}# Auto-generated Solana seed (32-byte base58). Replace with a Phantom export to use an existing wallet.\nSOLANA_PRIVATE_KEY=${value}\n`,
    { mode: 0o600 }
  );
  return { generated: true, value };
}

/**
 * Fill empty RPC_URL_ARBITRUM / RPC_URL_SOLANA in a wrangler.jsonc.
 * Leaves non-empty values alone.
 */
export function applyWalletRpcDefaults(wranglerPath: string): string[] {
  if (!existsSync(wranglerPath)) return [];
  let text = readFileSync(wranglerPath, "utf-8");
  const patched: string[] = [];
  const defaults: Record<string, string> = {
    RPC_URL_ARBITRUM: DEFAULT_RPC_URL_ARBITRUM,
    RPC_URL_SOLANA: DEFAULT_RPC_URL_SOLANA,
  };
  for (const [key, url] of Object.entries(defaults)) {
    const empty = new RegExp(`("${key}"\\s*:\\s*)""`);
    if (empty.test(text)) {
      text = text.replace(empty, `$1"${url}"`);
      patched.push(key);
    }
  }
  if (patched.length > 0) writeFileSync(wranglerPath, text);
  return patched;
}
